server:
  port: 3010
  host: '127.0.0.1'
s3:
  access_key: ''
  secret_key: ''
  file_acl: 'public-read'
  bucket:
    deployment: ''
    static: ''
upload:
  # Relative to the project directory
  path: '/tmp'
  # 000MB
  max_fields_size: 30
